apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: gitlab-hwservice-app
  namespace: master
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - http:
      paths:
      - path: /helloworld
        backend:
          serviceName: hwservice
          servicePort: 8080

